version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/devopspipe
permissions:
  - object: scripts/
    mode: 777
    type:
      - directory
hooks:
  ApplicationStart:
    - location: scripts/start-containers.sh
      timeout: 300
      runas: root
